<?php
define('importWordpressData', 'use admin tools');

/**
 * Implements hook_menu().
 */
function wordpress_data_import_menu() {
  $items['admin/config/wordpress_data_import'] = [
    'title' => t('Import wordpress data'),
    'page callback' => 'drupal_get_form',
    'page arguments' => ['wordpress_data_import_form'],
    'access arguments' => ['wordpress_data_import_form_submit'],
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
    'file' => 'src/includes/wordpress_data_import.admin.inc',
    'weight' => 100,
  ];
  return $items;
}

function wordpress_data_import_page() {
  return t("The Action Example provides three example 
                 actions which can be configured on 
                the <a href='admin/config/wordpress_data_import'>
                Actions configuration page</a>");
}